### ISSUE TITLE
Здравейте!

### ISSUE THREAD

**Issue by me-no-dev** [OLIMEX/ESP32-EVB#1]
Здравейте!
Казвам се Христо Гочков, работя за Еспресиф и в частност съм отговорен за Ардуино средата за ЕСП32. Понеже сме си сънародници :) реших да ви пиша и да ви кажа че ще се радвам ако можем да сме си полезни, пък и да ви оставя контакт :) Ако имате въпроси относно контролерите, не се колебайте да ги зададете.

**Comment by ESP32DE** [comment]
Fine! You are welcome Christo ;-)

best wishes
rudi ;-)

**Comment by TsvetanUsunov** [comment]
Здрасти, прати един имейл на info @ olimex com

**Comment by stankow** [comment]
Малко късно попадам на тази поща, чак след година. Работим с ESP32, много сме доволни ! Ценим много вашият принос ! Прехвърляме наш код от предишни Ардуино проекти и вашите библиотеки за ESP32 добре ни идват !  Поздрави, успех !

**Comment by me-no-dev** [comment]
Нищо :) тя офертата си е валидна и сега
