### ISSUE TITLE
Emac rx buff err in ETH example

### ISSUE THREAD

**Issue by gjongenelen** [OLIMEX/ESP32-EVB#11]
Hello,

I bought a ESP21-EVB Rev.C  board and am trying to run the ETH_PHY_demo program. Connection to the PHY is established, but I'm getting the following error:
`E (137287) emac: emac rx buf err!!`

Is this a result of using Rev.B examples on a Rev.C board?

No IP is assigned to the ethernet-port via DHCP btw.

**Comment by DanKoloff** [comment]
The software example was written for older version of ESP-IDF, it needs to be updated, for now follow the advice I posted here until we fix it: https://github.com/OLIMEX/ESP32-GATEWAY/issues/3

**Comment by gjongenelen** [comment]
Thanks, it works

**Comment by jovermann** [comment]
I see the same issue with the Olimex ETH_PHY_demo (also using a Rev C board). I can also confirm that the workaround pointed to by the link above works.

Concretely, the workaround is:
1. Use the ethernet example provided with the esp-idf. Do not use the ETH_PHY_demo at all.
2. Use these settings in make menuconfig (under "Example Configuration"):
CONFIG_PHY_TLK110=
CONFIG_PHY_LAN8720=y
CONFIG_PHY_ADDRESS=0
CONFIG_PHY_CLOCK_GPIO0_IN=y
CONFIG_PHY_CLOCK_GPIO0_OUT=
CONFIG_PHY_CLOCK_GPIO16_OUT=
CONFIG_PHY_CLOCK_GPIO17_OUT=
CONFIG_PHY_CLOCK_MODE=0
CONFIG_PHY_USE_POWER_PIN=
CONFIG_PHY_SMI_MDC_PIN=23
CONFIG_PHY_SMI_MDIO_PIN=18

**Comment by DanKoloff** [comment]
The examples had been updated and should work properly with the latest ESP-IDF.
