### ISSUE TITLE
Guys if you use KiCad nightly please at least give the version you used in the readme!

### ISSUE THREAD

**Issue by poeschlr** [OLIMEX/ESP32-EVB#17]
Projects created with nightlies are only guaranteed to work with that one version. Earlier nightlies and all stable releases will most likely not be able to open it. 
Even a later nightly builds can struggle as sometimes a file format modification is later removed again. 

_This has happened once in the version 5 development cycle. There where a few days where the 3d model offset value [at] used mm instead of inches. Later the at value was again used for inches whereas a new field was introduced for the metric stuff [offset]. So if you would open a project that was created within these few days with any other version of kicad, you would get the wrong 3d model offset._

---

It seems at least Rev D is made with a recent nightly. So with luck it is one from after the feature freeze. (Meaning the dangers described above should be minimized.)

**Comment by TsvetanUsunov** [comment]
KiCAD always embed the version which is used in the first line of PCB and SCH files:

(kicad_pcb (version 20170123) (host pcbnew "(2017-04-24 revision 50716c901)-makepkg")
