### ISSUE TITLE
ethernet can't be connected with ethernet

### ISSUE THREAD

**Issue by shubham7946** [OLIMEX/ESP32-EVB#18]
This type of error is coming while connecting with LAN to olimex.My connected network is of DHCP type.

E (1323) emac: Timed out waiting for PHY register 0x2 to have value 0x2000 (mask 0xffff). Current value 0xffff
E (2323) emac: Timed out waiting for PHY register 0x3 to have value 0xa210 (mask 0xfff0). Current value 0xffff
E (3323) emac: Timed out waiting for PHY register 0x2 to have value 0x2000 (mask 0xffff). Current value 0xffff
E (4323) emac: Timed out waiting for PHY register 0x3 to have value 0xa210 (mask 0xfff0). Current value 0xffff

Kindly suggest me solution.

**Comment by DanKoloff** [comment]
Did you try using exactly this demo: https://github.com/OLIMEX/ESP32-EVB/tree/master/SOFTWARE/ETH_PHY_demo ?

**Comment by maqtech** [comment]
Hi I tried to use the demo with a REV C, but the board does not connect to ethernet, could you please support me!

**Comment by DanKoloff** [comment]
What exactly happens? Is there some error message or where does it stop?

**Comment by DanKoloff** [comment]
Closing due to lack of reply and details. If the problem remains and new details emerge I'd reopen it.
