### ISSUE TITLE
The BOM does not have a suggested part number for the CR1

### ISSUE THREAD

**Issue by tracemils** [OLIMEX/ESP32-EVB#19]
Can the BOM be more detailed with suggested part numbers

**Comment by DanKoloff** [comment]
We can't recommend parts that we haven't used and the parts that we use are wholesale - you can't find them nor purchase small volumes. That is why we provide details on what to search for. In the case of the oscillator search for Q50MHz/25ppm/3V/4P/5x3.2mm.

I have narrowed it down to this search: https://www.digikey.com/short/jwhtbm

**Comment by tracemils** [comment]
many oscillators suggest having a decoupling capacitor between power supply and ground very close to the oscillator, which is missing in the design unless i am wrong.

**Comment by DanKoloff** [comment]
Seems answered, closing this issue.
