### ISSUE TITLE
 Ethernet demo Compatibility with ESP-IDF(v4.0)

### ISSUE THREAD

**Issue by ghost** [OLIMEX/ESP32-EVB#27]
I am working on olimex ESP32-EVB and using Ethernet interface for an application but after updating esp-idf to v4.0 the demo codes are not working. 
When will you update your Ethernet component and demo example for esp-idf v4.0?

**Comment by DanKoloff** [comment]
There is a demo for v4.0 here now: https://github.com/OLIMEX/ESP32-EVB/tree/master/SOFTWARE/ESP32-EVB_Ethernet_v4.0
