### ISSUE TITLE
Ethernet restart

### ISSUE THREAD

**Issue by iBobik** [OLIMEX/ESP32-EVB#30]
Hello,
I sometimes have issues with Ethernet stability (probably due power stagility or interferences). This could be easilly fixed by a restart of whole board (SW restart on ESP is not enough). Powering off or short circuit 3.3V with GND restarted it well enough. But I need to do it automatically.

So it seems like I need to restart Ethernet controller. Could I somehow restart it from ESP by it's GPIOs?

**Comment by DanKoloff** [comment]
"short circuit 3.3V with GND" is not good idea... better remove the 3.3V instead of short-circuiting the board...

The reset signal that is connected to the reset button is ESP_EN, it can be found on pin #33 of the EXT1 header. To reset the board you need to keep ESP_EN in low position and then release it back up. It is risky to connect it to ESP32's GPIO tho, you might shoot yourself in the foot.

**Comment by iBobik** [comment]
Thank you for reply.

Will be safe to ground ESP_EN by a transistor controlled by some GPIO?
Which transistor shoudl work?


Honza Pobořil

**Comment by DanKoloff** [comment]
First test directly with a free GPIO, place 1uF capacitor on the wire. It is worth testing the simple setup first.

**Comment by iBobik** [comment]
Hello,
I've tried to ground ESP_EN by 1-4 0,95uF capacitors, but restart not happened.

**Comment by iBobik** [comment]
Here someone recommended to just wire GPIO and RST:
https://www.researchgate.net/post/How-to-reboot-reset-ESP32-without-pressing-the-reboot-button-on-the-board

What could happen?

**Comment by DanKoloff** [comment]
Well I wrote the same: "First test directly with a free GPIO, place 1uF capacitor on the wire. It is worth testing the simple setup first."

**Comment by iBobik** [comment]
Sorry, I am not sure I understand you, so I draw it :-)

Here is what I tried:
<img width="715" alt="Snímek obrazovky 2021-04-30 v 17 31 48" src="https://user-images.githubusercontent.com/614232/116718229-08c49e00-a9da-11eb-8f76-4f1691c8dac0.png">

**Comment by iBobik** [comment]
Also tried this:
<img width="196" alt="Snímek obrazovky 2021-04-30 v 17 36 25" src="https://user-images.githubusercontent.com/614232/116718782-a0c28780-a9da-11eb-91ca-cafec3efb319.png">

**Comment by DanKoloff** [comment]
Why GPIO5 exactly? Did you toggle GPIO5 in those tests by software means?

Try with one of the GPIOs that are available at the UEXT connector - for example GPIO16 or GPIO13.

**Comment by iBobik** [comment]
U use GPIO5 because it is not used anywhere else. Yes, I toggled it by SW.
Is there something wrong with this?

I have not used UEXT pins because I use this connector for something else
(only GPIO 13, 14 and 15).


Honza Pobořil

**Comment by DanKoloff** [comment]
Just as a test try with one of the pins from the UEXT instead of GPIO5, for example GPIO16 which seems that you don't use for the other connection.
