### ISSUE TITLE
ESP32-EVB vs ESP32-EVB-IND

### ISSUE THREAD

**Issue by nagyrobi** [OLIMEX/ESP32-EVB#34]
I ordered an ESP32-EVB-IND but I think the mailman brought an ESP32-EVB. Is there any clear notation difference on the PCB that this actually is an IND version? It only has printed ESP32-EVB on it.
The first thing I noticed is that the relays are black and not orange as in the product photo on the website (RECOY LEG.5), this doesn't seem to comply with the -40+85C rated for the IND version board. That's what made me wonder, could it be that by mistake I did not receive an IND version?

I plan to use this board in harsh environment, I specifically need an IND version.

(Also having an ESP32-POE-ISO, which is clearly marked on the board as -ISO, that's why I would expect the -IND to be marked too.)

**Comment by DanKoloff** [comment]
All ESP32-EVB board variants use same PCB hence white print is the same. However, the Ethernet chip is different modification. One is suitable for wider temperature range. The regular version uses ~~LAN8720A~~ LAN8710A while the industrial uses ~~LAN8720Ai~~ LAN8710Ai.

Edit: Initial version had wrong chip variant.

**Comment by nagyrobi** [comment]
It's a 87**10**Ai:
![image](https://user-images.githubusercontent.com/1550668/147699887-d6440c5f-b13f-46af-a86e-6ee61666e2b8.png)

**Comment by DanKoloff** [comment]
Yes, my bad. It is 8710A and 8710Ai. This is also visible in the schematic. I've edited my previous post. The chip on your board is the industrial version.

Still I understand why it is not clear, this doesn't seem to be mentioned on the schematic. I will speak to the designers to generate Bill of Materials (BOM) for each board variant so I can upload it to GitHub.

The ESP32-POE and ESP32-POE-ISO have a lot of differences in the design to galvanically isolate the power supply from the POE and from the USB hence they have different PCBs. Still the IND versions just have few different components.

**Comment by nagyrobi** [comment]
It's just the question of how can the customer easily identify, check that he received the correct product.

I had doubts because the relays are weaker than the spec (but still within my requirements so it's fine with me)
