### ISSUE TITLE
ESP32-WROOVER kit code don't work on ESP32-EVB

### ISSUE THREAD

**Issue by DylanVautrin** [OLIMEX/ESP32-EVB#36]
Hi, 
I've made a code on ESP32-WROOVER-KIT, it connect to an wifi hotspot if it had the ssid and password, and if not, it create an hotspot to fill the right informations to connect to an wifi hotspot.
This code works on ESP32-WROOVER but it don't work on the ESP-EVB, is there any modifications needed to use a code for ESP32-WROOVER on a ESP32-EVB ?
Thanks

**Comment by DanKoloff** [comment]
These boards use different ESP32 modules as a main component.  ESP32-WROOVER-KIT uses ESP32-WROVER, while  ESP32-EVB uses ESP32-WROOM-32.

The biggest difference between the WROOM and the WROVER chips is that the WROVER has "SPI PSRAM" chip on the module along with the ESP32-D0WDQ6. Probably the code uses that SPI PSRAM and this SPI PSRAM is not available on the ESP32-WROOM32 chip.
