### ISSUE TITLE
BMP085

### ISSUE THREAD

**Issue by jukebox** [OLIMEX/ESP32-EVB#4]
do you have examples with BMP085 ?

**Comment by DanKoloff** [comment]
We don't have an example with ESP32-EVB, yet we have a number of examples. The Arduino example (with OLIMEXINO-328) would probably also work with ESP32-EVB out-of-the-box. Check the "Software" section of our product with BMP085: https://www.olimex.com/Products/Modules/Sensors/MOD-BMP085/open-source-hardware
