### ISSUE TITLE
ESP32-EVB_Ethernet_v4.4 compilation error

### ISSUE THREAD

**Issue by itsterit** [OLIMEX/ESP32-EVB#41]
I'm using an ESP32-EVB board and want to run a standard ethernet example.

![image](https://user-images.githubusercontent.com/49567814/215393661-e7b8ff2d-64f6-47e4-9002-8a3ba549924e.png)
![image](https://user-images.githubusercontent.com/49567814/215393794-da43d9cc-ca6f-4469-933a-4e48af1d2398.png)
![image](https://user-images.githubusercontent.com/49567814/215393859-ae7a5476-2527-4faa-acec-53db38cf045f.png)

after setting

![image](https://user-images.githubusercontent.com/49567814/215400632-60769ad7-01f8-4213-9eb3-31076a5f2d0b.png)

![image](https://user-images.githubusercontent.com/49567814/215400575-0ae90255-ec13-4231-837b-18ad8582443d.png)

**Comment by DanKoloff** [comment]
Did you try this instead: https://github.com/OLIMEX/ESP32-EVB/tree/master/SOFTWARE/ESP-IDF%20examples/ESP32-EVB_Ethernet_v4.4 ?

**Comment by DanKoloff** [comment]
Also you are using ESP-IDF 5.0 for a project clearly labeled as suitable for ESP-IDF 4.4?
