### ISSUE TITLE
Wifi to lan adapter.

### ISSUE THREAD

**Issue by Atlanta11** [OLIMEX/ESP32-EVB#42]
Hello is this also possible with the module ESP32-EVB?

![Schermafbeelding 2023-02-26 153405](https://user-images.githubusercontent.com/9640147/221416975-b69701a6-36e9-44e4-b3f6-e17b32e9211d.png)

Thanks in advance
Gino

**Comment by DanKoloff** [comment]
Yes. It is possible to use both WIFI and Ethernet, the hardware allows it. The question is whether the software allows it. I did some test for similar Olimex board, ESP32-GATEWAY, by combining two Arduino IDE examples - one for Ethernet, one for WIFI. Each interface had own IP address - WIFI has own IP address, Ethernet had own IP address. Both worked simultaneously.

There is an official support for Olimex ESP32-EVB in Arduino IDE for ESP32. My advice is to join either the espressif or the Arduino for ESP32 forums and check or ask for the others people's experience with using ESP32's Ethernet and WIFI simultaneously.
