### ISSUE TITLE
J1939 canbus Supported

### ISSUE THREAD

**Issue by samuelvvmm** [OLIMEX/ESP32-EVB#44]
Hello,

Is the J1939 CanBus protocol supported??

I would like reading NMEA2000 bus. Is Possible??

**Comment by samuelvvmm** [comment]
Hello,

Is the J1939 CanBus protocol supported??

I would like reading NMEA2000 bus. Is Possible??

**Comment by DanKoloff** [comment]
What is the hardware revision of the board that you have ? The CAN transceiver used until recently was Microchip's MCP2562-E, which is what most likely your board has. Check its documentation (or search online) on whether " J1939 CanBus" and/or "NMEA2000 bus" work with MCP2562.

**Comment by diplfranzhoepfinger** [comment]
Hi,

for J1939 and NMEA 2000 you need a Library. it is mainly a SW issue. (it is a HW issue too, as some EVB use a 3.3 V Transceiver, which is forbid on some Networks) 

look here: 
https://github.com/Open-Agriculture/AgIsoStack-plus-plus
for one Possible Solution, 

you will find many more in the net like this one: 
https://osb-connagtive.com/isobus/leistungen/software/isoaglibse/
