### ISSUE TITLE
Ethernet problem

### ISSUE THREAD

**Issue by Natsuchao** [OLIMEX/ESP32-EVB#45]
Can't get ethernet working in arduino sketch on my ESP32-EVB-EA-IND. Seems related with a chip id problem (lan8710) : 

E (101) lan87xx: lan87xx_init(499): wrong chip ID
E (101) esp_eth: esp_eth_driver_install(215): init phy failed

Any clue would be very appretiated.

Theo

**Comment by DanKoloff** [comment]
Try adding "delay(300);" or  "delay(500);" in the beginning of the setup, like:

void setup()
{
  delay(300);
  Serial.begin(115200);
  WiFi.onEvent(WiFiEvent);
  ETH.begin();
}

**Comment by Natsuchao** [comment]
It worked ! Thanks !

**Comment by diplfranzhoepfinger** [comment]
> It worked ! Thanks !
> […](#)

pls close then !
