### ISSUE TITLE
GPIO pins used by board hardware

### ISSUE THREAD

**Issue by quakec** [OLIMEX/ESP32-EVB#46]
Is there any information on what pins on the ESP32 are used with the onboard components, I see relays are 32 and 33 based only on a code example.  But what about the rest of the components such as IR receiver, SD card and LAN8720 chip?

**Comment by trevorXsingleton** [comment]
The information you are looking for in actually here on this github thread under hardware.  Not sure what board revision you have got as there have been many over the years.  I have put a pdf of the ESP32-EVB Rev I board below.

[ESP32-EVB_Rev_I_Schematic.pdf](https://github.com/OLIMEX/ESP32-EVB/files/11994875/ESP32-EVB_Rev_I_Schematic.pdf)

**Comment by quakec** [comment]
> The information you are looking for in actually here on this github thread under hardware. Not sure what board revision you have got as there have been many over the years. I have put a pdf of the ESP32-EVB Rev I board below.
> 
> [ESP32-EVB_Rev_I_Schematic.pdf](https://github.com/OLIMEX/ESP32-EVB/files/11994875/ESP32-EVB_Rev_I_Schematic.pdf)

Thank you for the quick response, I don't have a board yet, the product images suggest it is revision K but could be K1.  The schematic is well documented with component values. I'm also pleased the footprint is available on here too.  I look forward to working with this bit of kit!
