### ISSUE TITLE
Step CAD file of whole board ESP32-EWB

### ISSUE THREAD

**Issue by SurfingSpider** [OLIMEX/ESP32-EVB#49]
Can you add this STEP file to this github repo, which is the whole board with all on it components? I had to download KiCad to create it but it might help someone in the future making a case design.

[ESP32-EVB_Rev_K.zip](https://github.com/OLIMEX/ESP32-EVB/files/12267420/ESP32-EVB_Rev_K.zip)

**Comment by DanKoloff** [comment]
No, since we don't have the resources to verify it. As you pointed out it is simple enough to generate it via KiCAD (open the project, load the PCB, click File -> Export -> STEP...).
