### ISSUE TITLE
Reset / Power on is entering DownloadBoot mode

### ISSUE THREAD

**Issue by quakec** [OLIMEX/ESP32-EVB#50]
I have the ESP32-EVB Rev. K connected to a board I designed using the UEXT1 header, the schematic is below.

The issue I have is multiple resets are needed to get the board to boot SPI flash, sometimes it'll start up in SPI flash mode fine.

When I disconnect the GPIO2 pin between my board and the EVB board, the problem doesn't exist (starts up fine every single time).

In order to satisfy the condition which results in the ESP32 entering download boot mode both GPIO0 and GPIO2 are pulled down:
![image](https://github.com/OLIMEX/ESP32-EVB/assets/1788271/99367a02-588d-405f-9429-818d7b99aa4f)

I am seeking a solution here, realising I may have to go back to the drawing board. 
At this stage I have two questions:

1. If GPIO0 is pulled high internally, why is it randomly pulled down causing this?
2. Is there anything I can change on my circuit to prevent GPIO2 beign pulled down?

Q1 is a 2N2222A NPN transistor used to switch on leds built in to 3 x push buttons.  I had tried moving this over to GPIO15, however this prevents boot logs being sent over UART.
![image](https://github.com/OLIMEX/ESP32-EVB/assets/1788271/47ef79d4-6b09-4831-9d9f-48917292440d)

I am a novice at electronics so any advice would be greatly appreciated.

**Comment by quakec** [comment]
With some help I have resolved the pull down on GPIO2 by introducing R7 to bias voltage to the pin.

![image](https://github.com/OLIMEX/ESP32-EVB/assets/1788271/1513b774-e372-4691-bc30-8dd6432958a9)

Now I have another issue, which appears random at startup / reboot, the boot logs read:

![image](https://github.com/OLIMEX/ESP32-EVB/assets/1788271/2e8240fe-2802-41bf-996c-9b07b0fa3dfd)

I notice the GPIO0 bit flag is missing from the boot flags (reads 0xb) when it does fail.

![image](https://github.com/OLIMEX/ESP32-EVB/assets/1788271/2f2264ca-645e-4552-8700-2c01e7067f8c)

It will restart itself with the correct bit flag reflecting the state of GPIO0 being high, again this brings me back to my first question in my first post, I must add that this still occurs even with nothing connected to UEXT1.

**Comment by DanKoloff** [comment]
This reads like you've enabled watch dog and it expired and reboot... Are you sure you haven't enabled watchdog timer?
