### ISSUE TITLE
Is CAN library interrupt based

### ISSUE THREAD

**Issue by rvxfahim** [OLIMEX/ESP32-EVB#52]
Is the library given in the repo setup the CAN driver as interrupt driven, and then it sends frame to the freertos queue ?
or is it internally polling the buffer ?

**Comment by DanKoloff** [comment]
No idea. We only patched the original ESP32-Arduino-CAN library (https://github.com/miwagner/ESP32-Arduino-CAN) then added two examples for ESP32-EVB. The code open and available to analyze.
