### ISSUE TITLE
SD and MOD 2.8 TFT LCD

### ISSUE THREAD

**Issue by rvxfahim** [OLIMEX/ESP32-EVB#53]
In arduino framework I am already using the MOD 2.8 TFT LCD with the ESP32 EVB board, but I can't seem to find a way to use the SD card with any library because almost all libraries I checked use CS pin and the spi pins for the card are also not standard pins. Any guidance ? Thanks.
EDIT: I figured out Espressif SD_MMC library works, but I can see that the on board sd shares MOSI MISO clock lines with the TFT.

**Comment by DanKoloff** [comment]
I believe they can't be active simultaneously. But you can pause the SPI operation to access the 1-bit SD card then return to the display operation. Re-initialize each interface before usage. Notice that the SD card doesn't use SPI interface but 1-bit mode.
