### ISSUE TITLE
Power supply through barrel connector 5V/2A results in instable webserver

### ISSUE THREAD

**Issue by fredlcore** [OLIMEX/ESP32-EVB#54]
We now have several users who have reported that powering the EVB via the barrel connector with a 5V/2A power supply does power the board (i.e. LEDs are on), but network connectivity is shaky at best. We have experienced the same with power supplys over USB, but that seemed to have to do with low quality power supplies and the test for us is now that users should power the EVB via a laptop's USB to rule out a low quality power supply. So far, this has always led to a stable network connection.

Therefore, I wanted to check whether the power supply for the barrel connector on the EVB should really be just exactly 5V or whether there is a range as with other Olimex devices which you can power with 6-16V for example. Since the reports of users who have a problem with power supply via the barrel connector is significantly larger than the ones who complain about USB-powered boards, I wanted to make sure that this is not a design issue.
Thank you.

**Comment by TsvetanUsunov** [comment]
ESP32-EVB requires regulated exactly 5V power supply, applying more than 5V will damage the board.
I recommend you to use SY0605E https://www.olimex.com/Products/Power/SY0605E/ or SY1005 https://www.olimex.com/Products/Power/SY1005E/ adapters to power the board.
