### ISSUE TITLE
USB driver for MacOs Sonoma M2

### ISSUE THREAD

**Issue by stefan-tiva** [OLIMEX/ESP32-EVB#55]
I'm not able to install the USB driver for MacOs Sonoma on a Macbook Pro M2. 

Is there an update of this driver available?

**Comment by DanKoloff** [comment]
It is a new Mac, probably it already has built-in CH340 driver... But if you have issues check the official CH340 manufacturers repo:

https://github.com/WCHSoftGroup/ch34xser_macos

CH340 is popular USB-serial converter, there is good chance you can find info about MacOS installation online.

**Comment by stefan-tiva** [comment]
Thanks, I will check there
