### ISSUE TITLE
Question about the SD card's CS connection

### ISSUE THREAD

**Issue by fredlcore** [OLIMEX/ESP32-EVB#56]
I'm a bit puzzled about the connection of the chip select signal of the EVB's SD card reader:
![303183514-1eb60952-ae82-4b2c-8550-7a34d69c4f7d](https://github.com/OLIMEX/ESP32-EVB/assets/24660955/581f8e21-587c-4bcf-a331-e4f050f0a6dd)

My understanding of SPI is that CS is an active low signal that is to be set to logical low if the device is being accessed. Here, however, it is set to 3.3V constantly (through a 2.2k resistor). I read that if a device is the only SPI device, then CS can be tied to GND to have the device active all the time, but I don't understand how this is supposed to work here.

Is this therefore an error in the schematics or is it supposed to work that way and it's just my understanding of SPI that is wrong?

Thank you!

**Comment by TsvetanUsunov** [comment]
this is not CS but CD pin and should be pulled up

**Comment by fredlcore** [comment]
Thank you for your prompt and helpful answer, @TsvetanUsunov!
