### ISSUE TITLE
MicroPython compatibility?

### ISSUE THREAD

**Issue by riklaunim** [OLIMEX/ESP32-EVB#9]
I wonder if someone tried flashing this board with MicroPython for ESP32 and if so - which features are supported out of the box?

**Comment by magantiakhilchandra** [comment]
Well I was trying to use CAN. No modules for that. Says we can export a CAN module on to it and import but, I was not sucessful

**Comment by DanKoloff** [comment]
For the CAN look here: https://github.com/OLIMEX/ESP32-EVB/tree/master/SOFTWARE/CAN_demo
